### ISSUE TITLE
ShellHacks Icon disappears when screen width is at 1023 and in Sign Up form

### ISSUE THREAD

**Issue by boxslide15** [UPE-FIU/Web-ShellHacks#15]
<img width="1025" alt="Screen Shot 2019-04-11 at 4 54 27 PM" src="https://user-images.githubusercontent.com/7514088/55992494-b9886500-5c7a-11e9-8bb7-494b250c2aea.png">

**Comment by Jehfkemsy** [comment]
i had fixed this a while back ...forgot to cose it
