### ISSUE TITLE
menu items needs to stay active when selected

### ISSUE THREAD

**Issue by Jehfkemsy** [UPE-FIU/Web-ShellHacks#33]

**Comment by dvale94** [comment]
On my branch i have solved this issue, If you want to take a look at it. I would suggest changing the color of the active item so it does not clash when hovering over the other items. Also let me know if you would like the letters to be white when active. I noticed the clickable area of the item to be the word itself. Let me know if you would like me to make the entire block clickable.

**Comment by Jehfkemsy** [comment]
yeah, if you could make the entire bock clickable that'd be nice.....and, also lets change the active text to white.
@dvale94
