### ISSUE TITLE
Research a navbar implementation for the dashboard page

### ISSUE THREAD

**Issue by boxslide15** [UPE-FIU/Web-ShellHacks#9]
Make sure that it adheres to responsive design principles

**Comment by Svilla27** [comment]
found this for the side navbar implementation

https://www.w3schools.com/howto/howto_js_sidenav.asp

it has with and without animation but i'm not sure if you can have it as a static object on a site

**Comment by dannybarlos** [comment]
Found this video, although I'm not sure if it is what we are looking for:
https://www.youtube.com/watch?v=l6nmysZKHFU

**Comment by Svilla27** [comment]
Also found this on the same site as before:

https://www.w3schools.com/howto/howto_css_fixed_sidebar.asp

**Comment by Jehfkemsy** [comment]
im closing this and split it into smaller portions
